# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 740)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.UniversitiesGB = QtWidgets.QGroupBox(self.centralwidget)
        self.UniversitiesGB.setGeometry(QtCore.QRect(20, 30, 321, 71))
        self.UniversitiesGB.setObjectName("UniversitiesGB")
        self.UniversitiesCB = QtWidgets.QComboBox(self.UniversitiesGB)
        self.UniversitiesCB.setGeometry(QtCore.QRect(100, 30, 211, 21))
        self.UniversitiesCB.setObjectName("UniversitiesCB")
        self.UniversityLabel = QtWidgets.QLabel(self.UniversitiesGB)
        self.UniversityLabel.setGeometry(QtCore.QRect(0, 30, 111, 17))
        self.UniversityLabel.setObjectName("UniversityLabel")
        self.FacultiesGB = QtWidgets.QGroupBox(self.centralwidget)
        self.FacultiesGB.setGeometry(QtCore.QRect(20, 100, 301, 141))
        self.FacultiesGB.setObjectName("FacultiesGB")
        self.FacultyLabel = QtWidgets.QLabel(self.FacultiesGB)
        self.FacultyLabel.setGeometry(QtCore.QRect(10, 40, 81, 17))
        self.FacultyLabel.setObjectName("FacultyLabel")
        self.SpecialtyLabel = QtWidgets.QLabel(self.FacultiesGB)
        self.SpecialtyLabel.setGeometry(QtCore.QRect(10, 70, 121, 17))
        self.SpecialtyLabel.setObjectName("SpecialtyLabel")
        self.FacultiesCB = QtWidgets.QComboBox(self.FacultiesGB)
        self.FacultiesCB.setGeometry(QtCore.QRect(90, 30, 201, 25))
        self.FacultiesCB.setToolTipDuration(-1)
        self.FacultiesCB.setObjectName("FacultiesCB")
        self.SpecialtiesCB = QtWidgets.QComboBox(self.FacultiesGB)
        self.SpecialtiesCB.setGeometry(QtCore.QRect(10, 90, 281, 25))
        self.SpecialtiesCB.setObjectName("SpecialtiesCB")
        self.ExamsScoreGB = QtWidgets.QGroupBox(self.centralwidget)
        self.ExamsScoreGB.setGeometry(QtCore.QRect(20, 410, 271, 161))
        self.ExamsScoreGB.setObjectName("ExamsScoreGB")
        self.FirstSubjectLabel = QtWidgets.QLabel(self.ExamsScoreGB)
        self.FirstSubjectLabel.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.FirstSubjectLabel.setObjectName("FirstSubjectLabel")
        self.SecondSubjectLabel = QtWidgets.QLabel(self.ExamsScoreGB)
        self.SecondSubjectLabel.setGeometry(QtCore.QRect(10, 60, 67, 17))
        self.SecondSubjectLabel.setObjectName("SecondSubjectLabel")
        self.ScoreLabel = QtWidgets.QLabel(self.ExamsScoreGB)
        self.ScoreLabel.setGeometry(QtCore.QRect(10, 120, 67, 17))
        self.ScoreLabel.setObjectName("ScoreLabel")
        self.FirstSubjectCB = QtWidgets.QComboBox(self.ExamsScoreGB)
        self.FirstSubjectCB.setGeometry(QtCore.QRect(80, 30, 86, 25))
        self.FirstSubjectCB.setObjectName("FirstSubjectCB")
        self.SecondSubjectCB = QtWidgets.QComboBox(self.ExamsScoreGB)
        self.SecondSubjectCB.setGeometry(QtCore.QRect(80, 60, 86, 25))
        self.SecondSubjectCB.setObjectName("SecondSubjectCB")
        self.ScoreLE = QtWidgets.QLineEdit(self.ExamsScoreGB)
        self.ScoreLE.setGeometry(QtCore.QRect(80, 120, 113, 25))
        self.ScoreLE.setObjectName("ScoreLE")
        self.LanguageGroupLabel = QtWidgets.QLabel(self.ExamsScoreGB)
        self.LanguageGroupLabel.setGeometry(QtCore.QRect(10, 90, 67, 17))
        self.LanguageGroupLabel.setObjectName("LanguageGroupLabel")
        self.LanguageGroupCB = QtWidgets.QComboBox(self.ExamsScoreGB)
        self.LanguageGroupCB.setGeometry(QtCore.QRect(80, 90, 86, 25))
        self.LanguageGroupCB.setObjectName("LanguageGroupCB")
        self.PrivilegesGB = QtWidgets.QGroupBox(self.centralwidget)
        self.PrivilegesGB.setGeometry(QtCore.QRect(20, 240, 271, 161))
        self.PrivilegesGB.setObjectName("PrivilegesGB")
        self.ABRB = QtWidgets.QRadioButton(self.PrivilegesGB)
        self.ABRB.setGeometry(QtCore.QRect(10, 30, 112, 23))
        self.ABRB.setObjectName("ABRB")
        self.OrphanRB = QtWidgets.QRadioButton(self.PrivilegesGB)
        self.OrphanRB.setGeometry(QtCore.QRect(10, 60, 112, 23))
        self.OrphanRB.setObjectName("OrphanRB")
        self.CountrysideRB = QtWidgets.QRadioButton(self.PrivilegesGB)
        self.CountrysideRB.setGeometry(QtCore.QRect(10, 90, 112, 23))
        self.CountrysideRB.setObjectName("CountrysideRB")
        self.InvalidRB = QtWidgets.QRadioButton(self.PrivilegesGB)
        self.InvalidRB.setGeometry(QtCore.QRect(10, 120, 112, 23))
        self.InvalidRB.setObjectName("InvalidRB")
        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButton.setGeometry(QtCore.QRect(20, 580, 89, 25))
        self.SearchButton.setObjectName("SearchButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.menu.addAction(self.action_3)
        self.menu_2.addAction(self.action)
        self.menu_2.addAction(self.action_2)
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.UniversitiesGB.setTitle(_translate("MainWindow", "Университеты"))
        self.UniversityLabel.setText(_translate("MainWindow", "Университет:"))
        self.FacultiesGB.setTitle(_translate("MainWindow", "Специальности и Факультеты"))
        self.FacultyLabel.setText(_translate("MainWindow", "Факультет: "))
        self.SpecialtyLabel.setText(_translate("MainWindow", "Специальность: "))
        self.ExamsScoreGB.setTitle(_translate("MainWindow", "Здаваймые предметы"))
        self.FirstSubjectLabel.setText(_translate("MainWindow", "TextLabel"))
        self.SecondSubjectLabel.setText(_translate("MainWindow", "TextLabel"))
        self.ScoreLabel.setText(_translate("MainWindow", "TextLabel"))
        self.LanguageGroupLabel.setText(_translate("MainWindow", "TextLabel"))
        self.PrivilegesGB.setTitle(_translate("MainWindow", "Льготы"))
        self.ABRB.setText(_translate("MainWindow", "RadioButton"))
        self.OrphanRB.setText(_translate("MainWindow", "RadioButton"))
        self.CountrysideRB.setText(_translate("MainWindow", "RadioButton"))
        self.InvalidRB.setText(_translate("MainWindow", "RadioButton"))
        self.SearchButton.setText(_translate("MainWindow", "Найти"))
        self.menu.setTitle(_translate("MainWindow", "Справка"))
        self.menu_2.setTitle(_translate("MainWindow", "Язык"))
        self.action.setText(_translate("MainWindow", "Руский"))
        self.action_2.setText(_translate("MainWindow", "Қазақша"))
        self.action_3.setText(_translate("MainWindow", "О программе"))

